//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
public partial class cDBService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback Insert_PersonaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Update_PersonaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Insert_EmpresaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Update_EmpresaOperationCompleted;
    
    private System.Threading.SendOrPostCallback QuerryOperationCompleted;
    
    /// <remarks/>
    public cDBService()
    {
        this.Url = "http://www.webserviceitcrempleos.somee.com/Service1.asmx";
    }
    
    /// <remarks/>
    public event Insert_PersonaCompletedEventHandler Insert_PersonaCompleted;
    
    /// <remarks/>
    public event Update_PersonaCompletedEventHandler Update_PersonaCompleted;
    
    /// <remarks/>
    public event Insert_EmpresaCompletedEventHandler Insert_EmpresaCompleted;
    
    /// <remarks/>
    public event Update_EmpresaCompletedEventHandler Update_EmpresaCompleted;
    
    /// <remarks/>
    public event QuerryCompletedEventHandler QuerryCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Persona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Insert_Persona(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos) {
        object[] results = this.Invoke("Insert_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsert_Persona(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Insert_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsert_Persona(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Insert_PersonaAsync(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos) {
        this.Insert_PersonaAsync(correo, pasw, descrip, dir, nombre, ap1, ap2, cond, conocimientos, null);
    }
    
    /// <remarks/>
    public void Insert_PersonaAsync(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos, object userState) {
        if ((this.Insert_PersonaOperationCompleted == null)) {
            this.Insert_PersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_PersonaOperationCompleted);
        }
        this.InvokeAsync("Insert_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos}, this.Insert_PersonaOperationCompleted, userState);
    }
    
    private void OnInsert_PersonaOperationCompleted(object arg) {
        if ((this.Insert_PersonaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Insert_PersonaCompleted(this, new Insert_PersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_Persona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Update_Persona(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos) {
        object[] results = this.Invoke("Update_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate_Persona(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndUpdate_Persona(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Update_PersonaAsync(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos) {
        this.Update_PersonaAsync(correo, pasw, descrip, dir, nombre, ap1, ap2, cond, conocimientos, null);
    }
    
    /// <remarks/>
    public void Update_PersonaAsync(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos, object userState) {
        if ((this.Update_PersonaOperationCompleted == null)) {
            this.Update_PersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_PersonaOperationCompleted);
        }
        this.InvokeAsync("Update_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos}, this.Update_PersonaOperationCompleted, userState);
    }
    
    private void OnUpdate_PersonaOperationCompleted(object arg) {
        if ((this.Update_PersonaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Update_PersonaCompleted(this, new Update_PersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Empresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Insert_Empresa(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web) {
        object[] results = this.Invoke("Insert_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsert_Empresa(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Insert_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsert_Empresa(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Insert_EmpresaAsync(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web) {
        this.Insert_EmpresaAsync(mail, pasw, descrip, dir, nombre, ced, web, null);
    }
    
    /// <remarks/>
    public void Insert_EmpresaAsync(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web, object userState) {
        if ((this.Insert_EmpresaOperationCompleted == null)) {
            this.Insert_EmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_EmpresaOperationCompleted);
        }
        this.InvokeAsync("Insert_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web}, this.Insert_EmpresaOperationCompleted, userState);
    }
    
    private void OnInsert_EmpresaOperationCompleted(object arg) {
        if ((this.Insert_EmpresaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Insert_EmpresaCompleted(this, new Insert_EmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_Empresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Update_Empresa(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web) {
        object[] results = this.Invoke("Update_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate_Empresa(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndUpdate_Empresa(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Update_EmpresaAsync(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web) {
        this.Update_EmpresaAsync(mail, pasw, descrip, dir, nombre, ced, web, null);
    }
    
    /// <remarks/>
    public void Update_EmpresaAsync(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web, object userState) {
        if ((this.Update_EmpresaOperationCompleted == null)) {
            this.Update_EmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_EmpresaOperationCompleted);
        }
        this.InvokeAsync("Update_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web}, this.Update_EmpresaOperationCompleted, userState);
    }
    
    private void OnUpdate_EmpresaOperationCompleted(object arg) {
        if ((this.Update_EmpresaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Update_EmpresaCompleted(this, new Update_EmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Querry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable Querry(string tabla) {
        object[] results = this.Invoke("Querry", new object[] {
                    tabla});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginQuerry(string tabla, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Querry", new object[] {
                    tabla}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndQuerry(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void QuerryAsync(string tabla) {
        this.QuerryAsync(tabla, null);
    }
    
    /// <remarks/>
    public void QuerryAsync(string tabla, object userState) {
        if ((this.QuerryOperationCompleted == null)) {
            this.QuerryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerryOperationCompleted);
        }
        this.InvokeAsync("Querry", new object[] {
                    tabla}, this.QuerryOperationCompleted, userState);
    }
    
    private void OnQuerryOperationCompleted(object arg) {
        if ((this.QuerryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.QuerryCompleted(this, new QuerryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Insert_PersonaCompletedEventHandler(object sender, Insert_PersonaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Insert_PersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Insert_PersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Update_PersonaCompletedEventHandler(object sender, Update_PersonaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Update_PersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Update_PersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Insert_EmpresaCompletedEventHandler(object sender, Insert_EmpresaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Insert_EmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Insert_EmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Update_EmpresaCompletedEventHandler(object sender, Update_EmpresaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Update_EmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Update_EmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void QuerryCompletedEventHandler(object sender, QuerryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class QuerryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal QuerryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}
